name: Flutter CI
on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]
jobs:
    build:
        name: Build & Verify
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
        
          - name: Setup Flutter
            uses: subosito/flutter-action@v2
            with:
                flutter-version: '3.16.0'
                cache: true

          - name: Install Dependencies
            run: flutter pub get

          - name: Static Analysis
            run: flutter analyze --fatal-warnings

          - name: Run Unit Tests
            run: flutter-test

          - name: Build Release APK
            run: flutter build apk --release
